services:
  - type: web
    name: chirper
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: REDIS_URL
        fromService:
          type: redis
          name: chirper-redis
          property: connectionString

  - type: redis
    name: chirper-redis
    ipAllowList: [] # only allow internal connections
    plan: free # or choose a paid plan based on your needs